import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const APT_GROUPS = [
  // ─── China ───
  {
    id: 'apt1',
    name: 'APT1',
    aliases: ['Comment Crew', 'Comment Panda', 'GIF89a', 'Byzantine Candor', 'PLA Unit 61398'],
    lat: 31.2304, lng: 121.4737,
    nation: 'China',
    sponsor: 'PLA Unit 61398 (3PLA / SIGINT Bureau)',
    active_since: '2006',
    primary_targets: 'Aerospace, Defense, Energy, Telecom, IT, Finance (US and English-speaking)',
    known_tools: 'WEBC2, BISCUIT, Poison Ivy RAT, GhostNet, custom backdoors',
    notable_ops: 'Stole hundreds of terabytes from 141 organizations; Mandiant APT1 Report (2013) publicly exposed PLA Shanghai unit.',
    tlp_color: '#FF1744',
  },
  {
    id: 'apt10',
    name: 'APT10',
    aliases: ['MenuPass', 'Stone Panda', 'POTASSIUM', 'Red Apollo', 'CVNX', 'Cicada'],
    lat: 39.3434, lng: 117.3616,
    nation: 'China',
    sponsor: 'MSS Tianjin Bureau',
    active_since: '2009',
    primary_targets: 'Managed Service Providers (MSPs), Healthcare, Defense, Government (US, Japan, UK, India)',
    known_tools: 'PlugX, RedLeaves, UPPERCUT, Quasar RAT, ANEL, Cobalt Strike',
    notable_ops: 'Operation Cloud Hopper — compromised MSPs to pivot to clients globally; DOJ indictment 2018.',
    tlp_color: '#FF1744',
  },
  {
    id: 'apt40',
    name: 'APT40',
    aliases: ['Bronze Mohawk', 'GADOLINIUM', 'TEMP.Periscope', 'Leviathan', 'Kryptonite Panda', 'TA423'],
    lat: 20.0458, lng: 110.3417,
    nation: 'China',
    sponsor: 'MSS Hainan State Security Department (HSSD)',
    active_since: '2013',
    primary_targets: 'Maritime, Naval, Aerospace, Defense Contractors, Universities (COVID-19 research in 2020)',
    known_tools: 'AIRBREAK, FRESHAIR, BLACKCOFFEE, Derusbi, China Chopper webshell',
    notable_ops: 'IOCTA maritime espionage; COVID-19 vaccine research theft; Five Eyes joint advisory 2021.',
    tlp_color: '#FF1744',
  },
  {
    id: 'apt41',
    name: 'APT41',
    aliases: ['Double Dragon', 'Winnti', 'Barium', 'Brass Typhoon', 'Earth Baku', 'Wicked Panda'],
    lat: 39.9042, lng: 116.4074,
    nation: 'China',
    sponsor: 'MSS (dual espionage + financial crime)',
    active_since: '2012',
    primary_targets: 'Video games (supply chain), Healthcare, Telecom, Finance, Governments globally',
    known_tools: 'MESSAGETAP, SPECULOOS, Winnti malware, POISONPLUG, ShadowPad, Cobalt Strike',
    notable_ops: 'Supply-chain attack on CCleaner (2017); COVID-19 stimulus fraud; DOJ indictments 2020.',
    tlp_color: '#FF1744',
  },
  {
    id: 'volt-typhoon',
    name: 'Volt Typhoon',
    aliases: ['Bronze Silhouette', 'Vanguard Panda', 'DEV-0391', 'UNC3236'],
    lat: 39.9042, lng: 116.4074,
    nation: 'China',
    sponsor: 'PLA / MSS (pre-positioning for wartime disruption)',
    active_since: '2021',
    primary_targets: 'US Critical Infrastructure: Electric grids, Water, Telecom, Transportation (pre-positioning)',
    known_tools: 'Living-off-the-land binaries (LOLBins), custom KV-botnet, SOHO router compromise',
    notable_ops: 'Pre-positioning in US critical infrastructure for potential Taiwan conflict disruption; CISA advisory 2024.',
    tlp_color: '#FF1744',
  },
  {
    id: 'salt-typhoon',
    name: 'Salt Typhoon',
    aliases: ['FamousSparrow', 'GhostEmperor', 'UNC2286'],
    lat: 31.2304, lng: 121.4737,
    nation: 'China',
    sponsor: 'MSS',
    active_since: '2020',
    primary_targets: 'US telecom companies (AT&T, Verizon, T-Mobile); lawful intercept infrastructure (CALEA systems)',
    known_tools: 'SparrowDoor, ShadowPad, custom implants targeting CALEA intercept infrastructure',
    notable_ops: 'Compromised US carrier CALEA lawful-intercept backdoors used for wiretapping officials; disclosed 2024.',
    tlp_color: '#FF1744',
  },
  {
    id: 'hafnium',
    name: 'Hafnium',
    aliases: ['DEV-0190', 'Operation Exchange Marauder'],
    lat: 39.9042, lng: 116.4074,
    nation: 'China',
    sponsor: 'MSS (Chinese state-sponsored)',
    active_since: '2019',
    primary_targets: 'Defense contractors, Law firms, Infectious disease researchers, NGOs (US-based)',
    known_tools: 'China Chopper webshell, ASPXSPY, Covenant C2, Procdump, Nishang',
    notable_ops: 'Exploited zero-day chain in Exchange Server (ProxyLogon CVE-2021-26855) affecting 250,000+ servers.',
    tlp_color: '#FF1744',
  },

  // ─── Russia ───
  {
    id: 'apt28',
    name: 'APT28',
    aliases: ['Fancy Bear', 'Sofacy', 'STRONTIUM', 'Forest Blizzard', 'Pawn Storm', 'Sednit', 'Tsar Team'],
    lat: 55.7558, lng: 37.6173,
    nation: 'Russia',
    sponsor: 'GRU Unit 26165 (85th GTsSS)',
    active_since: '2004',
    primary_targets: 'NATO governments, Defense, Aerospace, Media (election interference), International organizations',
    known_tools: 'X-Agent, X-Tunnel, Zebrocy, GAMEFISH, SOURFACE, Seduploader, Lojax UEFI rootkit',
    notable_ops: 'DNC hack (2016); WADA/IOC athlete data leak; German Bundestag intrusion (2015); TV5Monde sabotage.',
    tlp_color: '#FF1744',
  },
  {
    id: 'apt29',
    name: 'APT29',
    aliases: ['Cozy Bear', 'The Dukes', 'Midnight Blizzard', 'Nobelium', 'YTTRIUM', 'Iron Hemlock'],
    lat: 55.5969, lng: 37.5167,
    nation: 'Russia',
    sponsor: 'SVR Foreign Intelligence Service',
    active_since: '2008',
    primary_targets: 'Government, Think tanks, Healthcare, Energy; persistent long-term espionage',
    known_tools: 'HAMMERTOSS, BEATDROP, CosmicDuke, MiniDuke, WellMess, SUNBURST, Brute Ratel C4',
    notable_ops: 'SolarWinds SUNBURST supply-chain attack (2020); DNC intrusion (2016); Microsoft corporate email (2024).',
    tlp_color: '#FF1744',
  },
  {
    id: 'sandworm',
    name: 'Sandworm',
    aliases: ['Voodoo Bear', 'ELECTRUM', 'Telebots', 'Iron Viking', 'Seashell Blizzard', 'GRU Unit 74455'],
    lat: 55.7558, lng: 37.6173,
    nation: 'Russia',
    sponsor: 'GRU Unit 74455 (GTsST / Sandworm)',
    active_since: '2009',
    primary_targets: 'Ukrainian critical infrastructure, Western energy grids, ICS/SCADA systems',
    known_tools: 'NotPetya, BlackEnergy, Industroyer/Crashoverride, Olympic Destroyer, Industroyer2, CADDYWIPER',
    notable_ops: 'NotPetya wiper (2017, $10B damage); Ukraine power grid blackouts (2015, 2016); Olympic Destroyer (2018).',
    tlp_color: '#FF1744',
  },
  {
    id: 'turla',
    name: 'Turla',
    aliases: ['Snake', 'Uroburos', 'Waterbug', 'Venomous Bear', 'Secret Blizzard', 'KRYPTON', 'WRAITH'],
    lat: 55.7558, lng: 37.6173,
    nation: 'Russia',
    sponsor: 'FSB Center 16',
    active_since: '2004',
    primary_targets: 'Governments, Embassies, Military, Research institutions globally (long-duration espionage)',
    known_tools: 'Snake/Uroburos rootkit, Kazuar, ComRAT, Carbon, JACO, Mosquito, HyperStack',
    notable_ops: 'Compromised 45 countries; hijacked Iranian APT34 infrastructure (2019); Snake botnet disrupted by FBI 2023.',
    tlp_color: '#FF1744',
  },
  {
    id: 'gamaredon',
    name: 'Gamaredon',
    aliases: ['Primitive Bear', 'Armageddon', 'ACTINIUM', 'Shuckworm', 'UAC-0010'],
    lat: 55.7558, lng: 37.6173,
    nation: 'Russia',
    sponsor: 'FSB Center 18 (Ukrainian operation)',
    active_since: '2013',
    primary_targets: 'Ukrainian government, military, NGOs; also targeting NATO allies and partners',
    known_tools: 'Pteranodon, Pterodo, SPRAT, Gammasteel, custom VBScript/PowerShell malware',
    notable_ops: 'Persistent targeting of Ukraine government since 2014; intensified operations since 2022 invasion.',
    tlp_color: '#FF9500',
  },
  {
    id: 'midnight-blizzard',
    name: 'Midnight Blizzard',
    aliases: ['Nobelium', 'APT29 subcluster', 'NobleBaron', 'StellarParticle'],
    lat: 55.5969, lng: 37.5167,
    nation: 'Russia',
    sponsor: 'SVR Foreign Intelligence Service',
    active_since: '2018',
    primary_targets: 'Government, Tech companies, Cloud providers (targeting identity/authentication infrastructure)',
    known_tools: 'SUNBURST, Teardrop, GoldMax, Sibot, GoldFinder, FOGGYWEB, MAGICWEB',
    notable_ops: 'SolarWinds supply-chain (2020); Microsoft senior leadership email access (Jan 2024).',
    tlp_color: '#FF1744',
  },
  {
    id: 'wizard-spider',
    name: 'Wizard Spider',
    aliases: ['TEMP.MixMaster', 'UNC1878', 'Ryuk operators', 'Conti operators'],
    lat: 48.3794, lng: 31.1656,
    nation: 'Russia',
    sponsor: 'Organized cybercrime (Russia/CIS-based)',
    active_since: '2016',
    primary_targets: 'Hospitals, Government, Critical infrastructure (ransomware for financial gain)',
    known_tools: 'Ryuk ransomware, Conti ransomware, TrickBot, BazarLoader, Anchor malware',
    notable_ops: 'Ryuk ransomware attacks on US hospitals during COVID-19; Conti attack on Ireland HSE (2021).',
    tlp_color: '#FF9500',
  },

  // ─── North Korea ───
  {
    id: 'lazarus-group',
    name: 'Lazarus Group',
    aliases: ['HIDDEN COBRA', 'Zinc', 'Diamond Sleet', 'APT38 parent', 'Bureau 121', 'Whois Team'],
    lat: 39.0292, lng: 125.7420,
    nation: 'North Korea',
    sponsor: 'RGB Bureau 121 (Reconnaissance General Bureau)',
    active_since: '2009',
    primary_targets: 'Financial institutions, Cryptocurrency, Defense, Media, Critical Infrastructure globally',
    known_tools: 'HOPLIGHT, FALLCHILL, DeltaCharlie, BLINDINGCAN, TraderTraitor, custom RATs',
    notable_ops: 'Sony Pictures hack (2014); Bangladesh Bank SWIFT heist $81M (2016); WannaCry (2017); Axie Infinity $620M (2022).',
    tlp_color: '#FF1744',
  },
  {
    id: 'apt38',
    name: 'APT38',
    aliases: ['BlueNoroff', 'Stardust Chollima', 'CryptoCore'],
    lat: 39.0292, lng: 125.7420,
    nation: 'North Korea',
    sponsor: 'RGB Bureau 121 (financial operations subunit)',
    active_since: '2014',
    primary_targets: 'Banks, Cryptocurrency exchanges, SWIFT network; financial theft to fund DPRK programs',
    known_tools: 'DYEPACK, FASTCASH, HERMES ransomware, custom SWIFT manipulation tools',
    notable_ops: 'Over $2B stolen from financial institutions; SWIFT Bangladesh heist; multiple crypto exchange hacks.',
    tlp_color: '#FF1744',
  },
  {
    id: 'kimsuky',
    name: 'Kimsuky',
    aliases: ['Velvet Chollima', 'Black Banshee', 'Thallium', 'Emerald Sleet', 'APT43'],
    lat: 39.0292, lng: 125.7420,
    nation: 'North Korea',
    sponsor: 'RGB (intelligence collection focused)',
    active_since: '2012',
    primary_targets: 'South Korean government, Think tanks, Nuclear/Policy experts, US/Japan officials',
    known_tools: 'BabyShark, AppleSeed, FlowerPower, GoldDragon, RandomQuery spear-phishing',
    notable_ops: 'Targeted ROK Unification Ministry; stole nuclear reactor designs; COVID vaccine research espionage.',
    tlp_color: '#FF9500',
  },
  {
    id: 'andariel',
    name: 'Andariel',
    aliases: ['Silent Chollima', 'Stonefly', 'Onyx Sleet', 'DarkSeoul'],
    lat: 39.0292, lng: 125.7420,
    nation: 'North Korea',
    sponsor: 'RGB Bureau 121 (sub-unit)',
    active_since: '2015',
    primary_targets: 'South Korean military, Defense contractors, Healthcare (ransomware), US defense supply chain',
    known_tools: 'Maui ransomware, DTrack, Dtrack, COPPERHEDGE, custom loaders',
    notable_ops: 'US healthcare ransomware attacks funding DPRK espionage; US-ROK joint advisory 2024.',
    tlp_color: '#FF9500',
  },

  // ─── Iran ───
  {
    id: 'apt34',
    name: 'APT34',
    aliases: ['OilRig', 'Helix Kitten', 'Cobalt Gypsy', 'IRN2', 'CHRYSENE'],
    lat: 35.7219, lng: 51.3347,
    nation: 'Iran',
    sponsor: 'MOIS (Ministry of Intelligence and Security)',
    active_since: '2014',
    primary_targets: 'Middle East governments, Financial sector, Energy, Telecom, Chemical',
    known_tools: 'POWRUNER, BONDUPDATER, RDAT, DNSpionage, Karkoff, LIONTAIL',
    notable_ops: 'Middle East telecoms espionage; DNS hijacking campaign; toolset leaked by Lab Dookhtegan (2019).',
    tlp_color: '#FF9500',
  },
  {
    id: 'apt33',
    name: 'APT33',
    aliases: ['Elfin', 'Refined Kitten', 'Magnallium', 'Peach Sandstorm', 'HOLMIUM'],
    lat: 35.7219, lng: 51.3347,
    nation: 'Iran',
    sponsor: 'IRGC-linked contractors',
    active_since: '2013',
    primary_targets: 'Aerospace, Aviation, Petrochemical (US, Saudi Arabia, South Korea)',
    known_tools: 'SHAPESHIFT, TURNEDUP, NANOCORE, NETWIRE, ALFA Shell, DropShot dropper',
    notable_ops: 'Shamoon wiper campaign against Saudi Aramco precursor; spear-phishing US aerospace firms.',
    tlp_color: '#FF9500',
  },
  {
    id: 'apt35',
    name: 'APT35',
    aliases: ['Charming Kitten', 'Phosphorus', 'Mint Sandstorm', 'ITG18', 'TA453', 'NewsBeef'],
    lat: 35.7219, lng: 51.3347,
    nation: 'Iran',
    sponsor: 'IRGC (Islamic Revolutionary Guard Corps)',
    active_since: '2014',
    primary_targets: 'US/Israeli officials, Academics, Journalists, Nuclear experts, Human rights activists',
    known_tools: 'HYPERSCRAPE, POWERSTAR, PowerLess backdoor, BellaCiao, custom phishing kits',
    notable_ops: 'Targeted Trump/Biden campaign officials (2020); Gaza war-period espionage; IAEA inspector targeting.',
    tlp_color: '#FF9500',
  },
  {
    id: 'muddywater',
    name: 'MuddyWater',
    aliases: ['Static Kitten', 'Seedworm', 'MERCURY', 'Mango Sandstorm', 'TA450', 'TEMP.Zagros'],
    lat: 35.7219, lng: 51.3347,
    nation: 'Iran',
    sponsor: 'MOIS (Ministry of Intelligence and Security)',
    active_since: '2017',
    primary_targets: 'Middle East/Central Asia governments, Telecom, Defense (Turkey, Pakistan, UAE, Jordan)',
    known_tools: 'POWERSTATS, SHARPSTATS, Ligolo, PhonyC2, SimpleHell, PowGoop',
    notable_ops: 'Persistent Middle East government targeting; supply-chain attacks on IT providers in region.',
    tlp_color: '#FF9500',
  },

  // ─── USA (Alleged/Attributed) ───
  {
    id: 'equation-group',
    name: 'Equation Group',
    aliases: ['EQGRP', 'Tilded Team (alleged NSA TAO)'],
    lat: 39.1084, lng: -76.7717,
    nation: 'United States',
    sponsor: 'NSA TAO (Tailored Access Operations) [alleged]',
    active_since: '2001',
    primary_targets: 'Iran nuclear program, Russia, China, Middle East governments [alleged]',
    known_tools: 'EQUATIONDRUG, GRAYFISH, DOUBLEPULSAR, ETERNALBLUE, Fanny worm, custom HDD firmware implants',
    notable_ops: 'Stuxnet co-authorship (with Israel); leaked toolset by Shadow Brokers 2016-17; ETERNALBLUE enabled WannaCry/NotPetya.',
    tlp_color: '#FF1744',
  },
  {
    id: 'longhorn',
    name: 'Longhorn / The Lamberts',
    aliases: ['The Lamberts', 'Longhorn', 'Vault 7 tools (Wikileaks)'],
    lat: 38.9529, lng: -77.1465,
    nation: 'United States',
    sponsor: 'CIA Operations Support Branch [alleged via Vault 7 leaks]',
    active_since: '2007',
    primary_targets: 'Governments, Telecom, Finance in Middle East, Europe, Asia, Africa',
    known_tools: 'Fluxwire, Corentry, BaldEagle, Plexor, GreenLambert, YetiLambert (Vault 7)',
    notable_ops: 'Vault 7 leak (2017) exposed CIA\'s alleged offensive cyber tools; Longhorn linked to Vault 7 by Symantec.',
    tlp_color: '#FFD700',
  },

  // ─── Israel ───
  {
    id: 'unit-8200-apt',
    name: 'Unit 8200 Offensive (Duqu/Flame authors)',
    aliases: ['Equation Group co-author (Stuxnet/Duqu)', 'alleged IDF Unit 8200'],
    lat: 32.1239, lng: 34.8325,
    nation: 'Israel',
    sponsor: 'IDF Unit 8200 / Mossad [alleged]',
    active_since: '2007',
    primary_targets: 'Iranian nuclear program (Stuxnet); Middle East industrial control systems',
    known_tools: 'Stuxnet, Duqu, Flame, Gauss (joint US-Israel development alleged)',
    notable_ops: 'Stuxnet destroyed ~1000 Iranian centrifuges at Natanz (2010); most sophisticated cyber weapon ever deployed.',
    tlp_color: '#FF1744',
  },

  // ─── Other ───
  {
    id: 'apt36',
    name: 'APT36',
    aliases: ['Transparent Tribe', 'ProjectM', 'Mythic Leopard', 'COPPER FIELDSTONE'],
    lat: 33.6844, lng: 73.0479,
    nation: 'Pakistan',
    sponsor: 'ISI (Inter-Services Intelligence) [attributed]',
    active_since: '2016',
    primary_targets: 'Indian military, government, defense contractors; Afghan government',
    known_tools: 'CrimsonRAT, ObliqueRAT, ElizaRAT, CapraRAT (Android), POSEIDON',
    notable_ops: 'Targeting Indian Army personnel via fake military apps; widespread spear-phishing of Indian defense.',
    tlp_color: '#FF9500',
  },
  {
    id: 'sidewinder',
    name: 'SideWinder',
    aliases: ['T-APT-04', 'Rattlesnake', 'Hardcore Nationalist', 'Baby Elephant'],
    lat: 28.6139, lng: 77.2090,
    nation: 'India',
    sponsor: 'Indian military intelligence [alleged]',
    active_since: '2012',
    primary_targets: 'Pakistan military and government, China, Nepal, Sri Lanka, Bangladesh',
    known_tools: 'Custom .NET loaders, ReverseRat, ModifiedElizaRAT, JS downloaders, mobile implants',
    notable_ops: 'Extensive targeting of Pakistani armed forces; over 1000 attacks attributed since 2012.',
    tlp_color: '#FFD700',
  },
  {
    id: 'bahamut',
    name: 'Bahamut',
    aliases: ['The Bahamut', 'WIRTE subgroup (alleged)', 'mercenary APT'],
    lat: 25.2048, lng: 55.2708,
    nation: 'UAE (proxy)',
    sponsor: 'Alleged UAE government via private contractor',
    active_since: '2016',
    primary_targets: 'Middle East governments, Journalists, Human rights activists, Kashmir separatists',
    known_tools: 'Custom Android/iOS spyware, fake VPN apps, WhatsApp spyware, credential phishing',
    notable_ops: 'Targeted Sikh separatists in India; Saudi dissidents; operated fake news sites for influence ops.',
    tlp_color: '#FF9500',
  },
  {
    id: 'dark-caracal',
    name: 'Dark Caracal',
    aliases: ['Lebanese GDGS APT', 'Pallas'],
    lat: 33.8547, lng: 35.8623,
    nation: 'Lebanon',
    sponsor: 'Lebanese General Directorate of General Security (GDGS)',
    active_since: '2012',
    primary_targets: 'Military, Government, Finance, Journalists globally (30+ countries)',
    known_tools: 'Bandook RAT, CrossRAT, FinFisher (purchased), custom Android trojans',
    notable_ops: 'Multi-platform espionage using Bandook from Lebanese government building; EFF/Lookout report 2018.',
    tlp_color: '#FF9500',
  },
  {
    id: 'fin7',
    name: 'FIN7',
    aliases: ['Carbanak', 'Navigator Group', 'ELBRUS', 'Carbon Spider', 'Sangria Tempest'],
    lat: 50.4501, lng: 30.5234,
    nation: 'Russia / Ukraine',
    sponsor: 'Organized cybercrime group (not state-sponsored)',
    active_since: '2015',
    primary_targets: 'Point-of-sale systems, Restaurant chains, Hotels, Casinos; financial theft',
    known_tools: 'Carbanak, GRIFFON, BOOSTWRITE, RDFSNIFFER, Cobalt Strike, BadUSB attacks',
    notable_ops: 'Stole >$1B from financial institutions and retailers; compromised Chipotle, Arby\'s, Red Robin; multiple arrests.',
    tlp_color: '#FF9500',
  },
];

export async function GET() {
  try {
    const groups = APT_GROUPS.map(g => ({ ...g }));
    return NextResponse.json(
      { groups, total: groups.length, timestamp: new Date().toISOString() },
      { headers: { 'Cache-Control': 'public, s-maxage=86400' } }
    );
  } catch {
    return NextResponse.json({ data: [] }, { status: 500 });
  }
}
