import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

const SIGINT_STATIONS = [
  // ─── ECHELON Network (Five Eyes) ───
  { id: 'menwith-hill', name: 'RAF Menwith Hill', lat: 54.0022, lng: -1.6936, operator: 'NSA / GCHQ', nation: 'UK / US', type: 'SIGINT', targets: 'Military, diplomatic, commercial SATCOM and microwave relay interception across Europe', program: 'ECHELON / FORNSAT', notes: 'Largest SIGINT station in the world; ~30 radomes; intercepts Intelsat, Eutelsat, Inmarsat traffic.' },
  { id: 'pine-gap', name: 'Pine Gap (JDFPG)', lat: -23.7958, lng: 133.7369, operator: 'NSA / CIA / ASD', nation: 'Australia / US', type: 'SIGINT', targets: 'Asia, Middle East, South Asia SATCOM and missile telemetry collection', program: 'ECHELON / RAINFALL', notes: 'Most important SIGINT station outside the continental US; tracks missile launches and intercepts.' },
  { id: 'waihopai', name: 'Waihopai SIGINT Station', lat: -41.7033, lng: 173.8558, operator: 'GCSB / NSA', nation: 'New Zealand / US', type: 'COMSAT', targets: 'Pacific and Asia-Pacific Intelsat satellite traffic', program: 'ECHELON', notes: 'Two radomes intercept Intelsat and PanAmSat traffic; part of ECHELON global network.' },
  { id: 'geraldton', name: 'Geraldton SIGINT Station', lat: -28.7979, lng: 114.6171, operator: 'ASD', nation: 'Australia', type: 'COMSAT', targets: 'Indian Ocean and Asia-Pacific satellite communications', program: 'ECHELON', notes: 'ASD satellite intercept station; covers Indian Ocean Intelsat orbital arc.' },
  { id: 'shoal-bay', name: 'Shoal Bay Receiving Station', lat: -12.4500, lng: 130.9000, operator: 'ASD', nation: 'Australia', type: 'SIGINT', targets: 'South-East Asia military and government communications', program: 'ECHELON', notes: 'ASD facility targeting Indonesian and regional government and military traffic.' },
  { id: 'gchq-bude', name: 'GCHQ Bude / Morwenstow', lat: 50.8259, lng: -4.5427, operator: 'GCHQ / NSA', nation: 'UK / US', type: 'cable_tap', targets: 'Trans-Atlantic fiber-optic cable traffic; internet backbone interception', program: 'TEMPORA / ECHELON', notes: 'TEMPORA program taps ~25% of trans-Atlantic fiber cables; stores internet data for 3 days, metadata 30.' },
  { id: 'leitrim-cse', name: 'CFS Leitrim', lat: 45.3328, lng: -75.6225, operator: 'CSE', nation: 'Canada', type: 'SIGINT', targets: 'Americas, Atlantic, Caribbean government and military communications', program: 'ECHELON', notes: 'Canadian ECHELON node outside Ottawa; primary CSE SIGINT collection facility.' },
  { id: 'cfs-masset', name: 'CFS Masset', lat: 54.0179, lng: -132.1200, operator: 'CSE / Canadian Forces', nation: 'Canada', type: 'SIGINT', targets: 'Pacific Ocean military and commercial communications, Russian Pacific Fleet', program: 'ECHELON', notes: 'Pacific SIGINT collection on Haida Gwaii island; monitors trans-Pacific traffic.' },
  { id: 'cfs-alert', name: 'CFS Alert', lat: 82.5018, lng: -62.3481, operator: 'CSE / Canadian Forces', nation: 'Canada', type: 'SIGINT', targets: 'Russian military and diplomatic Arctic communications', program: 'ECHELON', notes: 'World\'s northernmost inhabited settlement; strategic Arctic SIGINT position.' },
  { id: 'misawa-sigint', name: 'Misawa SIGINT Center', lat: 40.7030, lng: 141.3680, operator: 'NSA / JASDF', nation: 'US / Japan', type: 'SIGINT', targets: 'Russian Pacific Fleet, North Korean military, Chinese military SIGINT', program: 'ECHELON / FORNSAT', notes: 'Joint USAF-NSA-JASDF facility; massive antenna arrays for regional SIGINT collection.' },
  { id: 'bad-aibling', name: 'Bad Aibling Station (BND)', lat: 47.8737, lng: 11.9822, operator: 'BND / NSA (former)', nation: 'Germany', type: 'COMSAT', targets: 'European, Middle Eastern, Russian satellite and microwave communications', program: 'ECHELON / EIKONAL', notes: 'Transferred from NSA to BND in 2004; EIKONAL program shared BND intercepts with NSA.' },

  // ─── NSA Domestic Collection Sites ───
  { id: 'nsa-fort-meade-main', name: 'NSA Fort Meade (Main Campus)', lat: 39.1084, lng: -76.7717, operator: 'NSA', nation: 'US', type: 'SIGINT', targets: 'Global SIGINT analysis, processing, and tasking hub; XKEYSCORE operations', program: 'XKEYSCORE / PRISM / MUSCULAR', notes: 'NSA HQ; processes petabytes of intercepted communications daily.' },
  { id: 'nsa-san-antonio', name: 'NSA / CSS Texas (NSAT)', lat: 29.4241, lng: -98.4936, operator: 'NSA', nation: 'US', type: 'SIGINT', targets: 'Latin America, Gulf, Middle East SIGINT; regional analysis hub', program: 'XKEYSCORE', notes: 'NSA Texas at Lackland AFB; regional SIGINT processing and analysis center.' },
  { id: 'nsa-augusta', name: 'NSA / CSS Georgia (NSAG)', lat: 33.4735, lng: -82.0105, operator: 'NSA', nation: 'US', type: 'cyber', targets: 'Cyber threat analysis, Army cyber integration, SIGINT support', program: 'XKEYSCORE', notes: 'NSA Georgia at Fort Eisenhower; primary Army Cyber Command integration site.' },
  { id: 'nsa-oahu', name: 'NSA / CSS Hawaii (NSAH)', lat: 21.4367, lng: -158.1925, operator: 'NSA', nation: 'US', type: 'SIGINT', targets: 'Pacific SIGINT, Chinese and North Korean military, regional cable taps', program: 'ECHELON / XKEYSCORE', notes: 'Pacific regional hub; Snowden worked here before leaking NSA documents.' },
  { id: 'nsa-utah-dc', name: 'NSA Utah Data Center (UCDC)', lat: 40.6218, lng: -112.0219, operator: 'NSA', nation: 'US', type: 'SIGINT', targets: 'Global data storage and processing for all NSA collection programs', program: 'PRISM / XKEYSCORE', notes: '1.5 million sq ft; stores yottabytes of encrypted traffic for cryptanalysis and future access.' },

  // ─── Russian FAPSI/FSB/GRU SIGINT ───
  { id: 'lourdes-cuba', name: 'Lourdes SIGINT Base', lat: 22.9417, lng: -82.2167, operator: 'GRU / FSB (revived)', nation: 'Russia', type: 'SIGINT', targets: 'US military, government, and commercial communications from Cuban listening post', program: 'SORM', notes: 'Russia operated this facility 1964-2002; reportedly re-activating signals collection capabilities.' },
  { id: 'yasenevo-sigint', name: 'SVR / FAPSI Yasenevo', lat: 55.5969, lng: 37.5167, operator: 'SVR / FSB FSO', nation: 'Russia', type: 'SIGINT', targets: 'Foreign government, diplomatic, and intelligence communications globally', program: 'SORM', notes: 'Russian foreign intelligence SIGINT analysis and processing hub within SVR complex.' },
  { id: 'tartus-sigint', name: 'Tartus SIGINT Node', lat: 34.8886, lng: 35.8866, operator: 'GRU', nation: 'Russia', type: 'SIGINT', targets: 'Mediterranean naval communications, NATO exercises, Middle East military traffic', program: 'SORM', notes: 'GRU signals collection co-located with Russian naval base at Tartus, Syria.' },
  { id: 'arctic-intercept-severomorsk', name: 'Severomorsk SIGINT Station', lat: 69.0694, lng: 33.4347, operator: 'GRU / FSB', nation: 'Russia', type: 'radar', targets: 'Norwegian Sea NATO traffic, UK-Iceland-Greenland gap submarine communications', program: 'SORM', notes: 'Arctic SIGINT station monitoring NATO naval and air traffic in the Greenland-Iceland-UK gap.' },
  { id: 'murmansk-elint', name: 'Murmansk ELINT Station', lat: 68.9585, lng: 33.0827, operator: 'GRU SIGINT', nation: 'Russia', type: 'radar', targets: 'NATO maritime radar emissions, submarine acoustic signatures in Barents Sea', program: 'SORM', notes: 'Electronic intelligence collection against NATO naval forces in the Barents and Norwegian Seas.' },

  // ─── Chinese PLA-SSF SIGINT ───
  { id: 'hainan-ssf', name: 'Hainan SIGINT Base (Lingshui)', lat: 18.2200, lng: 109.5742, operator: 'PLA-SSF', nation: 'China', type: 'SIGINT', targets: 'South China Sea military traffic, US carrier strike group communications, ASEAN', program: 'PLA-SSF Network', notes: 'PLA Strategic Support Force primary South China Sea SIGINT collection facility.' },
  { id: 'djibouti-china-sigint', name: 'PLA Djibouti SIGINT Node', lat: 11.5251, lng: 43.0498, operator: 'PLA-SSF / PLA Navy', nation: 'China', type: 'SIGINT', targets: 'Red Sea shipping, US/French base communications, African Union diplomatic traffic', program: 'PLA-SSF', notes: 'SIGINT collection co-located with China\'s first overseas military base.' },
  { id: 'xiamen-ssf', name: 'PLA SSF Xiamen Station', lat: 24.4800, lng: 118.1000, operator: 'PLA-SSF', nation: 'China', type: 'SIGINT', targets: 'ROC military and government communications, US Pacific forces', program: 'PLA-SSF', notes: 'Taiwan Strait SIGINT collection facility targeting Taiwanese military communications.' },
  { id: 'fiery-cross-sigint', name: 'Fiery Cross Reef SIGINT Array', lat: 9.5541, lng: 114.2203, operator: 'PLA-SSF / PLAN', nation: 'China', type: 'radar', targets: 'South China Sea maritime traffic, US and allied naval operations', program: 'PLA-SSF', notes: 'Advanced SIGINT and radar arrays on artificially expanded Fiery Cross Reef.' },
  { id: 'myanmar-china-sigint', name: 'Great Coco Island (alleged)', lat: 14.1167, lng: 93.3667, operator: 'PLA-SSF (alleged)', nation: 'China / Myanmar', type: 'SIGINT', targets: 'Alleged SIGINT collection monitoring Indian naval facilities on Andaman and Nicobar Islands', program: 'PLA-SSF', notes: 'Alleged Chinese SIGINT facility on Myanmar-administered island; disputed but reported by multiple analysts.' },

  // ─── GCHQ Overseas / UK Sites ───
  { id: 'gchq-cheltenham-main', name: 'GCHQ Cheltenham (The Doughnut)', lat: 51.8957, lng: -2.0779, operator: 'GCHQ', nation: 'UK', type: 'SIGINT', targets: 'Global; primary UK SIGINT processing hub across all collection streams', program: 'TEMPORA / ECHELON / MUSCULAR', notes: 'UK SIGINT HQ; processes intercepts from all GCHQ collection programs and Five Eyes sharing.' },
  { id: 'raf-akrotiri-sigint', name: 'RAF Akrotiri SIGINT (SBA)', lat: 34.5900, lng: 32.9887, operator: 'GCHQ / RAF', nation: 'UK', type: 'SIGINT', targets: 'Middle East military communications, Syria, Lebanon, Turkey, Israel intercepts', program: 'TEMPORA', notes: 'GCHQ collection site in UK Sovereign Base Area Cyprus; critical for Middle East SIGINT.' },
  { id: 'ascension-island-sigint', name: 'Ascension Island SIGINT', lat: -7.9462, lng: -14.3559, operator: 'GCHQ / NSA', nation: 'UK', type: 'COMSAT', targets: 'Atlantic satellite traffic; South Atlantic and African government communications', program: 'ECHELON', notes: 'Mid-Atlantic UK territory; GCHQ/NSA joint satellite intercept station.' },

  // ─── Undersea Cable Tap Points ───
  { id: 'cable-tap-bermuda', name: 'Atlantic Cable Tap (Bermuda Junction)', lat: 32.3078, lng: -64.7505, operator: 'NSA / GCHQ', nation: 'US / UK', type: 'cable_tap', targets: 'Trans-Atlantic fiber cables carrying European-American internet and voice traffic', program: 'TEMPORA / MUSCULAR', notes: 'Alleged NSA/GCHQ tap point on trans-Atlantic submarine cable landing in Bermuda.' },
  { id: 'cable-tap-cornwall', name: 'Bude Cable Landing Station', lat: 50.8279, lng: -4.5434, operator: 'GCHQ', nation: 'UK', type: 'cable_tap', targets: 'TAT-14, Apollo, Yellow/Atlantic Crossing cable systems; trans-Atlantic internet traffic', program: 'TEMPORA', notes: 'GCHQ TEMPORA intercepts cables at this Cornwall landing point; direct fiber tap on international cables.' },
  { id: 'cable-tap-singapore', name: 'SQX Cable Station (Singapore)', lat: 1.3521, lng: 103.8198, operator: 'ASD / NSA (alleged)', nation: 'Australia / US (alleged)', type: 'cable_tap', targets: 'Asia-Pacific submarine cables; SEA-ME-WE, FLAG, and C2C cable systems', program: 'ECHELON (alleged)', notes: 'Alleged Five Eyes collection on Singapore cable hub handling majority of Asia-Pacific traffic.' },
  { id: 'cable-tap-hawaii', name: 'Hawaii Cable Landing Point', lat: 21.3069, lng: -157.8583, operator: 'NSA', nation: 'US', type: 'cable_tap', targets: 'Trans-Pacific submarine cables; Asia-US and Australia-US internet backbone', program: 'XKEYSCORE', notes: 'NSA intercepts Pacific cable systems at Hawaii landing points; closest US territory to Asia-Pacific cables.' },

  // ─── Other National SIGINT ───
  { id: 'isnu-8200', name: 'Unit 8200 Urim Base', lat: 31.3214, lng: 34.6160, country: 'Israel', operator: 'IDF Unit 8200', nation: 'Israel', type: 'SIGINT', targets: 'Iranian, Palestinian, Lebanese, Arab state military and government SIGINT', program: 'Israeli SIGINT', notes: 'Primary IDF SIGINT collection site in Negev; targets Iranian nuclear program communications.' },
  { id: 'bnd-pullach', name: 'BND Headquarters Pullach', lat: 48.0267, lng: 11.5156, operator: 'BND', nation: 'Germany', type: 'SIGINT', targets: 'Russian, Middle Eastern, Chinese government communications; EIKONAL NATO-shared intercepts', program: 'EIKONAL / BND-NSA cooperation', notes: 'German foreign intelligence HQ; shared intercepts with NSA via EIKONAL program 2004-2013.' },
  { id: 'dgse-domme', name: 'DGSE Domme SIGINT Station', lat: 44.8014, lng: 1.2195, operator: 'DGSE', nation: 'France', type: 'SIGINT', targets: 'African, Middle Eastern, Russian communications; French sphere SIGINT', program: 'FRENCHELON', notes: 'DGSE\'s primary SIGINT collection facility; part of French FRENCHELON system.' },
  { id: 'raw-india', name: 'RAW Technical Division (New Delhi)', lat: 28.6139, lng: 77.2090, operator: 'RAW / NTRO', nation: 'India', type: 'SIGINT', targets: 'Pakistani military and government, Chinese military, Indian Ocean shipping', program: 'Indian SIGINT', notes: 'Indian SIGINT operations targeting Pakistan ISI and PLA; expanding satellite intercept capabilities.' },
  { id: 'masint-andaman', name: 'Andaman and Nicobar SIGINT', lat: 11.7401, lng: 92.6586, operator: 'Indian Armed Forces / NTRO', nation: 'India', type: 'radar', targets: 'Strait of Malacca shipping, PLA Navy movements, Bay of Bengal traffic', program: 'Indian SIGINT', notes: 'India\'s SIGINT hub monitoring South China Sea approaches and PLA Navy operations.' },
  { id: 'aivd-netherlands', name: 'AIVD/MIVD Netherlands SIGINT', lat: 52.3676, lng: 4.9041, operator: 'AIVD / MIVD', nation: 'Netherlands', type: 'cyber', targets: 'Russian APT groups; Dutch intelligence famously penetrated Cozy Bear (APT29)', program: 'NATO intelligence sharing', notes: 'AIVD/MIVD observed APT29 hacking US entities in 2014-2015 and alerted US partners.' },
  { id: 'maroc-dged', name: 'DGED Rabat SIGINT', lat: 33.9716, lng: -6.8498, operator: 'DGED (Morocco)', nation: 'Morocco', type: 'SIGINT', targets: 'Algerian military, Sahel insurgent networks, Western Sahara communications', program: 'Pegasus customer', notes: 'Moroccan intelligence SIGINT; reportedly used NSO Pegasus against Algerian and French targets.' },
  { id: 'sbu-ukraine', name: 'SBU Cyber / SIGINT Kyiv', lat: 50.4501, lng: 30.5234, operator: 'SBU', nation: 'Ukraine', type: 'cyber', targets: 'Russian GRU and FSB operations; real-time battlefield SIGINT from front lines', program: 'EU/NATO intelligence sharing', notes: 'Ukrainian Security Service SIGINT extensively sharing Russian military intercepts with NATO allies.' },
];

export async function GET() {
  try {
    const stations = SIGINT_STATIONS.map(s => ({ ...s }));
    return NextResponse.json(
      { stations, total: stations.length, timestamp: new Date().toISOString() },
      { headers: { 'Cache-Control': 'public, s-maxage=86400' } }
    );
  } catch {
    return NextResponse.json({ data: [] }, { status: 500 });
  }
}
